"""add uaps mock tables

Revision ID: 502ed726affa
Revises: f3a7c1d8e4b2
Create Date: 2026-10-04 20:47:21.124880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '502ed726affa'
down_revision: Union[str, Sequence[str], None] = 'f3a7c1d8e4b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uaps',
    sa.Column('id_uaps', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('bairro', sa.String(length=120), nullable=False),
    sa.Column('endereco', sa.String(length=200), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id_uaps')
    )
    op.create_table('estoque_uaps',
    sa.Column('id_estoque', sa.Integer(), nullable=False),
    sa.Column('id_uaps', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('REGULAR', 'NPH', 'GLARGINA', 'LISPRO', name='insulin_type_mock'), nullable=False),
    sa.Column('apresentacao', sa.String(length=60), nullable=False),
    sa.Column('quantidade_disponivel', sa.Integer(), nullable=False),
    sa.Column('nivel_disponibilidade', sa.Enum('ALTO', 'MEDIO', 'BAIXO', 'CRITICO', 'INDISPONIVEL', name='availability_level'), nullable=False),
    sa.Column('lote', sa.String(length=60), nullable=False),
    sa.Column('validade', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_uaps'], ['uaps.id_uaps'], ),
    sa.PrimaryKeyConstraint('id_estoque')
    )
    op.create_index(op.f('ix_estoque_uaps_id_uaps'), 'estoque_uaps', ['id_uaps'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_estoque_uaps_id_uaps'), table_name='estoque_uaps')
    op.drop_table('estoque_uaps')
    op.drop_table('uaps')
    # ### end Alembic commands ###
